app = "estatecore-backend-floral-hill-9253"

[build]

[deploy]
  release_command = "flask --app estatecore_backend.wsgi db upgrade"

[env]
  PORT = "8080"
  FLASK_ENV = "production"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
  [[services.ports]]
    port = 443

  [[services.http_checks]]
    interval = "10s"
    grace_period = "30s"
    method = "GET"
    path = "/healthz"
    protocol = "http"
    timeout = "2s"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
