[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip']

[phases.install]
dependsOn = ['setup']
cmds = ['cd estatecore_backend && python -m pip install -r requirements.txt']

[phases.build]
dependsOn = ['install']

[start]
cmd = 'cd estatecore_backend && python -m gunicorn wsgi:app --bind 0.0.0.0:$PORT'